version: '3'
services:
  web:
    build: ./webapp
    restart: always
    ports:
      - '7777:7777'
    networks:
      - app-network

  e2e:
    image: cypress
    build: ./e2e
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://s00i105i.bcaexpertise.org:7777/plop
    command: npx cypress run
    volumes:
      - ./e2e/cypress:/app/cypress
      - ./e2e/cypress.json:/app/cypress.json
    networks:
      - app-network

networks:
  app-network:
    external: true
